apiVersion: v1
kind: ConfigMap
metadata:
  name: portal
data:
  server-host: "0.0.0.0"
  server-port: "80"
  log-format: "json"
  base-url: "https://portal.dev.plugins.vultisig.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: portal
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  hmac-secret: "CHANGE_ME_IN_PRODUCTION"
