apiVersion: v1
kind: ConfigMap
metadata:
  name: portal
data:
  server-host: "0.0.0.0"
  server-port: "80"
  log-format: "json"
  base-url: "https://portal.dev.plugins.vultisig.com"
  max-api-keys-per-plugin: "5"
