apiVersion: v1
kind: ConfigMap
metadata:
  name: verifier
data:
  server-host: "0.0.0.0"
  server-port: "80"
  log-format: "json"
  auth-nonce-expiry-minutes: "15"
  fees-recipient-white-list: '["0x1234567890123456789012345678901234567890"]'
