apiVersion: v1
kind: ConfigMap
metadata:
  name: rpc
data:
  zcash: "https://zcash-mainnet.core.chainstack.com/9b440bcb25e4b43a8a18360d49ab9299"
  xrp: "https://xrplcluster.com"
  ethereum: "https://api.vultisig.com/eth/"
  arbitrum: "https://api.vultisig.com/arb/"
  avalanche: "https://api.vultisig.com/avax/"
  bsc: "https://api.vultisig.com/bsc/"
  base: "https://api.vultisig.com/base/"
  blast: "https://api.vultisig.com/blast/"
  optimism: "https://api.vultisig.com/opt/"
  polygon: "https://api.vultisig.com/polygon/"
  solana: "https://api.vultisig.com/solana/"
  cronos: "https://cronos-mainnet.core.chainstack.com/9b440bcb25e4b43a8a18360d49ab9299"
  zksync: "https://zksync-mainnet.core.chainstack.com/9b440bcb25e4b43a8a18360d49ab9299"
