apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-indexer
  labels:
    app: tx-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tx-indexer
  template:
    metadata:
      labels:
        app: tx-indexer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: tx-indexer
          image: busybox
          command: ["/app/main"]
          ports:
            - containerPort: 8088
              name: metrics
          env:
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: uri
            - name: LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: verifier
                  key: log-format
            - name: INTERVAL
              value: "10s"
            - name: ITERATION_TIMEOUT
              value: "3m"
            - name: MARK_LOST_AFTER
              value: "3h"
            - name: CONCURRENCY
              value: "50"
            - name: METRICS_ENABLED
              value: "true"
            - name: METRICS_HOST
              value: "0.0.0.0"
            - name: METRICS_PORT
              value: "8088"
            - name: RPC_XRP_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: xrp
            - name: RPC_ETHEREUM_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: ethereum
            - name: RPC_ARBITRUM_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: arbitrum
            - name: RPC_AVALANCHE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: avalanche
            - name: RPC_BSC_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: bsc
            - name: RPC_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: base
            - name: RPC_BLAST_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: blast
            - name: RPC_OPTIMISM_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: optimism
            - name: RPC_POLYGON_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: polygon
            - name: RPC_SOLANA_URL
              valueFrom:
                configMapKeyRef:
                  name: rpc
                  key: solana
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
